# Generated by Django 5.1 on 2024-10-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genetic_diseases', models.TextField(blank=True, null=True)),
                ('family_hyst', models.TextField(blank=True, null=True)),
                ('working', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '3_ana_vitae',
            },
        ),
        migrations.CreateModel(
            name='DopolnitelnieStatisticheskieDannye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazovanie_dlitelnost', models.CharField(blank=True, max_length=255, null=True)),
                ('kolichestvo_detey', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dopolnitelnie_statisticheskie_dannie',
            },
        ),
    ]
