# Generated by Django 5.1 on 2024-10-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dopolnitelniestatisticheskiedannye_obrazovanie_dlitelnost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopolnitelniestatisticheskiedannye',
            name='obrazovanie_dlitelnost',
            field=models.IntegerField(blank=True, db_column='Obrazovanie_(dlitelnost)', null=True),
        ),
    ]
