# Generated by Django 5.1 on 2024-10-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dopolnitelniestatisticheskiedannye_obrazovanie_dlitelnost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnaVitae',
        ),
        migrations.DeleteModel(
            name='DopolnitelnieStatisticheskieDannye',
        ),
    ]
